### ISSUE TITLE
请问方便请教你几个问题么？

### ISSUE THREAD

**Issue by xuxc** [hy2014/hy2014.github.com#2]
我用Hindex 建立索引表之后，使用Filter查询200万数据，需要40秒，感觉索引表没有起作用，请问是不是有特别的方式调用？

**Comment by hy2014** [comment]
没有啊，这得看你的索引多少还有你region的多少，个人感觉 发自网易邮箱大师 在2014年11月03日 21:44 ，xuxc写道： 我用Hindex 建立索引表之后，使用Filter查询200万数据，需要40秒，感觉索引表没有起作用，请问是不是有特别的方式调用？ — Reply to this email directly or view it on GitHub.

**Comment by xuxc** [comment]
5个region，索引表1800W条记录，我可以加你QQ，或者Email你么？我的地址xuxc1120@hotmail.com

**Comment by hy2014** [comment]
wangsheng.0376@163.com, 其实我也是不太会啊

**Comment by hy2014** [comment]
你建了这么多索引， 有什么用呢

**Comment by hy2014** [comment]
我不清楚同时， 如果有多个索引同时起作用， 是不是会多个索引， 同时触发Get查询, 如果是这样， 可能多个索引同时触发， 会耗费时间

**Comment by xuxc** [comment]
anoopsjohn说 ：As this query covers 2 index, we will have 2 index scanners which retrieve data (at server side) simultaneously and using AND find the data rks. If there can be single index on both these columns that will be better any way. 

这个scan是自动拆分成2个index scanner 么？

**Comment by hy2014** [comment]
是的， hbase index尝试解析index， 如果发现trigger了多个index的话， 会触发多个index scanner。

**Comment by hy2014** [comment]
你先试试， 删除多个index之后， 是不是时间减少了？

**Comment by xuxc** [comment]
我之前部署过一个集群，也是相同的配置，相同的系统，建立相同的表，那个里面建立了多个索引，400W数据时候利用过滤器查询大约1秒得到结果（结果集只有几条），后来重新部署了一下就出现了这样的问题，不知道是哪里出错了。。
建表和查询的JAVA代码我发您邮箱了，多谢指正了~

**Comment by hy2014** [comment]
我看看吧，不一定弄出来，如果配置一样，那就是数据的问题了 发自网易邮箱大师 在2014年11月03日 22:29 ，xuxc写道： 我之前部署过一个集群，也是相同的配置，相同的系统，建立相同的表，那个里面建立了多个索引，400W数据时候利用过滤器查询大约1秒得到结果（结果集只有几条），后来重新部署了一下就出现了这样的问题，不知道是哪里出错了。。 建表和查询的JAVA代码我发您邮箱了，多谢指正了~ — Reply to this email directly or view it on GitHub.

**Comment by xuxc** [comment]
请教一下，全数据集一共100多个字段，大约50个字段可能被检索，按条件检索出来之后希望得到这一行的所有列，这样的话该怎么配置Hbase？
听说phoenix4.1集成了hindex,但是只能索引到通过Phoenix client插入的数据，我通过kettle spoon插入的数据不能索引到，而且select \* 操作的时候 全表扫描，index不起作用。我想知道hindex是否可以解决这些不足。
多谢指教。

**Comment by hy2014** [comment]
对于索引，我感觉使用solr会更合适。 发自网易邮箱大师 在2014年11月03日 22:40 ，xuxc写道： 请教一下，全数据集一共100多个字段，大约50个字段可能被检索，按条件检索出来之后希望得到这一行的所有列，这样的话该怎么配置Hbase？ 听说phoenix4.1集成了hindex,但是只能索引到通过Phoenix client插入的数据，我通过kettle spoon插入的数据不能索引到，而且select \* 操作的时候 全表扫描，index不起作用。我想知道hindex是否可以解决这些不足。 多谢指教。 — Reply to this email directly or view it on GitHub.

**Comment by hy2014** [comment]
我倾向于ngdada的hbase-indexer 发自网易邮箱大师 在2014年11月03日 22:40 ，xuxc写道： 请教一下，全数据集一共100多个字段，大约50个字段可能被检索，按条件检索出来之后希望得到这一行的所有列，这样的话该怎么配置Hbase？ 听说phoenix4.1集成了hindex,但是只能索引到通过Phoenix client插入的数据，我通过kettle spoon插入的数据不能索引到，而且select \* 操作的时候 全表扫描，index不起作用。我想知道hindex是否可以解决这些不足。 多谢指教。 — Reply to this email directly or view it on GitHub.

**Comment by xuxc** [comment]
请问有相关的solr系统可以借鉴的么？ 没接触过那个所以不太了解。
你说的hbase-indexer  是LiLy么？那个可以满足全字段搜索的需求么？希望是实时的查询，因为想接入web直接做查询，不知道这样设计合不合理？

**Comment by hy2014** [comment]
是的，通过replication，应该是可以实现实时的 发自网易邮箱大师 在2014年11月03日 22:46 ，xuxc写道： 请问有相关的solr系统可以借鉴的么？ 没接触过那个所以不太了解。 你说的hbase-indexer 是LiLy么？那个可以满足全字段搜索的需求么？希望是实时的查询，因为想接入web直接做查询，不知道这样设计合不合理？ — Reply to this email directly or view it on GitHub.

**Comment by hy2014** [comment]
而且从hindex的官方介绍看，数据量大了之后scan的性能提高的不是太明显。 发自网易邮箱大师 在2014年11月03日 22:46 ，xuxc写道： 请问有相关的solr系统可以借鉴的么？ 没接触过那个所以不太了解。 你说的hbase-indexer 是LiLy么？那个可以满足全字段搜索的需求么？希望是实时的查询，因为想接入web直接做查询，不知道这样设计合不合理？ — Reply to this email directly or view it on GitHub.

**Comment by xuxc** [comment]
多谢了，我先看看那个怎么部署，可能还要向你请教，
麻烦你了。

**Comment by hy2014** [comment]
其实我也是新手 发自网易邮箱大师 在2014年11月03日 22:51 ，xuxc写道： 多谢了，我先看看那个怎么部署，可能还要向你请教， 麻烦你了。 — Reply to this email directly or view it on GitHub.

**Comment by xuxc** [comment]
您谦虚啦~
我是真的入门新手，有的系统都是第一次安装，也走了好多弯路，LILY我也没接触过，我先看看怎么使用，遇到问题再请教你哈

**Comment by xuxc** [comment]
您好，按您说的，在FilterList中只设置单个Filter，返回27个结果只需要800ms，但是FilterList添加另一个Filter时，就变成了40秒。个人推断是第二个过滤器检索的列上没有建索引，导致全表扫瞄。:-)
如果猜测正确，若Hindex的过滤器顺序为：在第一个Filter过滤之后的结果集中再筛选第二个过滤器的内容，可能会带来性能上的提高，不知这样是否可行？

**Comment by xuxc** [comment]
你好，请问对于已经利用hindex建的表，怎么查看那些列已经建有索引？怎么知道查询的事后是否调用了索引？

**Comment by hy2014** [comment]
是否触发索引，可以看我的博客， 查询索引，应该可以通过查询schema 获取结果。 PS:你用hindex是问了学习还是真的在用，如果真的在项目中用，需要好好评估一下 发自网易邮箱大师 在2014年11月11日 15:17 ，xuxc写道： 你好，请问对于已经利用hindex建的表，怎么查看那些列已经建有索引？怎么知道查询的事后是否调用了索引？ — Reply to this email directly or view it on GitHub.

**Comment by xuxc** [comment]
用来学习的，刚接触，所以有些地方还不是很熟悉

**Comment by hy2014** [comment]
好吧 发自网易邮箱大师 在2014年11月11日 15:25 ，xuxc写道： 用来学习的，刚接触，所以有些地方还不是很熟悉 — Reply to this email directly or view it on GitHub.
